ALTER TABLE KURS3.TP_TRAFFIC_DOC
 DROP PRIMARY KEY CASCADE;

DROP TABLE KURS3.TP_TRAFFIC_DOC CASCADE CONSTRAINTS;

CREATE TABLE KURS3.TP_TRAFFIC_DOC
(
  TRAFFIC_DOC_ID  NUMBER                        NOT NULL,
  SIGN_ID         NUMBER,
  DOC_NUM         VARCHAR2(25 BYTE),
  DOC_DATE        DATE,
  OPERATOR        VARCHAR2(250 BYTE),
  DOLGNOST        VARCHAR2(250 BYTE),
  PRINT_DATE      DATE
)
TABLESPACE KURS3
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE KURS3.TP_TRAFFIC_DOC IS 'для хранения документов по движению паспартов';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_DOC.TRAFFIC_DOC_ID IS 'ид';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_DOC.SIGN_ID IS 'ид подписи';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_DOC.DOC_NUM IS 'номер документа пердачи паспорта';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_DOC.DOC_DATE IS 'дата документа';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_DOC.OPERATOR IS 'кото передал (ФИО)';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_DOC.DOLGNOST IS 'кто передал (должность)';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_DOC.PRINT_DATE IS 'дата печати';



CREATE UNIQUE INDEX KURS3.TP_TRAFFIC_DOC_PK ON KURS3.TP_TRAFFIC_DOC
(TRAFFIC_DOC_ID)
LOGGING
TABLESPACE KURS3
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE KURS3.TP_TRAFFIC_DOC ADD (
  CONSTRAINT TP_TRAFFIC_DOC_PK
  PRIMARY KEY
  (TRAFFIC_DOC_ID)
  USING INDEX KURS3.TP_TRAFFIC_DOC_PK);
