DROP TABLE KURS3.TP_TRAFFIC_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE KURS3.TP_TRAFFIC_HISTORY
(
  TP_TRAFFIC_ID       NUMBER,
  TP_ID               NUMBER,
  USER_ID             NUMBER,
  LAST_CHANGE         DATE,
  WORK_PLACE_LINK_ID  NUMBER,
  ACTION              VARCHAR2(1 BYTE),
  ACTION#USER_ID      NUMBER,
  ACTION#CHANGE       DATE,
  NSORT               NUMBER,
  DOC_NUM             VARCHAR2(25 BYTE),
  DOC_DATE            DATE,
  TRAFFIC_DOC_ID      NUMBER
)
TABLESPACE KURS3
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE KURS3.TP_TRAFFIC_HISTORY IS 'История движения техпаспорта (все) названия полей  из таблицы TECHPASPORT_TRAFFIC';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_HISTORY.ACTION IS 'U-изменения, D-удаление, I-добавление ';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_HISTORY.ACTION#USER_ID IS 'пользователь который провел опрепацию';

COMMENT ON COLUMN KURS3.TP_TRAFFIC_HISTORY.ACTION#CHANGE IS 'дата операции';



ALTER TABLE KURS3.TP_TRAFFIC_HISTORY ADD (
  CONSTRAINT TP_TRAFFIC_HISTORY_R02 
  FOREIGN KEY (WORK_PLACE_LINK_ID) 
  REFERENCES KURS3.TP_WORK_PLACE_LINK (WORK_PLACE_LINK_ID),
  CONSTRAINT TP_TRAFFIC_HISTORY_R03 
  FOREIGN KEY (TRAFFIC_DOC_ID) 
  REFERENCES KURS3.TP_TRAFFIC_DOC (TRAFFIC_DOC_ID));
