DROP TABLE KURS3.TP_WORK_PLACE_LINK_OPTIONS CASCADE CONSTRAINTS;

CREATE TABLE KURS3.TP_WORK_PLACE_LINK_OPTIONS
(
  WORK_PLACE_LINK_ID  NUMBER,
  WORKPLACE_ID        NUMBER
)
TABLESPACE KURS3
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE KURS3.TP_WORK_PLACE_LINK_OPTIONS IS 'таблица для назначения дополнительных прав для осуществления движения техпаспорта';

COMMENT ON COLUMN KURS3.TP_WORK_PLACE_LINK_OPTIONS.WORK_PLACE_LINK_ID IS 'идентификатор движения';

COMMENT ON COLUMN KURS3.TP_WORK_PLACE_LINK_OPTIONS.WORKPLACE_ID IS 'идентификатор рабочего места';



ALTER TABLE KURS3.TP_WORK_PLACE_LINK_OPTIONS ADD (
  CONSTRAINT TP_WORK_PLACE_LINK_OPTIONS_R01 
  FOREIGN KEY (WORK_PLACE_LINK_ID) 
  REFERENCES KURS3.TP_WORK_PLACE_LINK (WORK_PLACE_LINK_ID));

GRANT DELETE, INSERT, SELECT, UPDATE ON KURS3.TP_WORK_PLACE_LINK_OPTIONS TO KURS3_ADM;
