ALTER TABLE KURS3.TP_WORK_PLACE_LINK
 DROP PRIMARY KEY CASCADE;

DROP TABLE KURS3.TP_WORK_PLACE_LINK CASCADE CONSTRAINTS;

CREATE TABLE KURS3.TP_WORK_PLACE_LINK
(
  FROM_WP             NUMBER,
  TO_WP               NUMBER,
  WORK_PLACE_LINK_ID  NUMBER                    NOT NULL,
  DOC_TYPE_ID         NUMBER,
  STATUS_ID           NUMBER
)
TABLESPACE KURS3
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE KURS3.TP_WORK_PLACE_LINK IS 'таблица для определения возможного пути передачи техпаспорта';

COMMENT ON COLUMN KURS3.TP_WORK_PLACE_LINK.FROM_WP IS 'Отправитель ТП(кл.132)';

COMMENT ON COLUMN KURS3.TP_WORK_PLACE_LINK.TO_WP IS 'Получатель ТП(кл.132)';

COMMENT ON COLUMN KURS3.TP_WORK_PLACE_LINK.DOC_TYPE_ID IS 'Тип документа передачи(кл. 134)';

COMMENT ON COLUMN KURS3.TP_WORK_PLACE_LINK.STATUS_ID IS 'Статус ТП(кл. 135)';



CREATE UNIQUE INDEX KURS3.WORKPLACELINK_PK ON KURS3.TP_WORK_PLACE_LINK
(WORK_PLACE_LINK_ID)
LOGGING
TABLESPACE KURS3
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE KURS3.TP_WORK_PLACE_LINK ADD (
  CONSTRAINT WORKPLACELINK_PK
  PRIMARY KEY
  (WORK_PLACE_LINK_ID)
  USING INDEX KURS3.WORKPLACELINK_PK);

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE ON KURS3.TP_WORK_PLACE_LINK TO KURS3_ADM;

GRANT SELECT ON KURS3.TP_WORK_PLACE_LINK TO OKRUG;
