CREATE OR REPLACE VIEW V_KURS3_SCAN_VIVERKA_DATE AS
SELECT
--  19.11.2013  DIK
 v.obj_id    as delo_id,
 v.record_dt as viverka_date
FROM
(SELECT ROW_NUMBER () OVER (PARTITION BY l.obj_id ORDER BY l.record_dt desc) num
                                ,l.record_dt
                                ,l.obj_id
                            FROM KURS3.verify_filer l
                           WHERE
                                  l.op_type = 1
                                 AND l.obj_type_id = 9 -- EA_DELO.STATUS
                                 AND l.new_value = '2' -- EA_DELO.STATUS = Выверено
                                 ) v
where v.num=1 --последняя по дате запись т.к.  ORDER BY - desc
-- GRANT SELECT ON V_KURS3_SCAN_VIVERKA_DATE TO OKRUG;
-- GRANT SELECT ON V_KURS3_SCAN_VIVERKA_DATE TO SCAN;
-- GRANT SELECT ON V_KURS3_SCAN_VIVERKA_DATE TO PUBLIC;
-- CREATE SYNONYM o51.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o52.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o53.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o54.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o55.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o56.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o57.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o58.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o59.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o60.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o61.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o62.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;
-- CREATE SYNONYM o63.V_KURS3_SCAN_VIVERKA_DATE FOR KURS3.V_KURS3_SCAN_VIVERKA_DATE;;
